### ISSUE TITLE
downloading

### ISSUE THREAD

**Issue by dotuxx** [gotkrypto76/yiff.party-downloader#2]
Hey! When the program see the files with the same name, they replace each others, and some part of content disapear. Can you please fix it??
i tryed to download from this creator: 323910 (texic)

**Comment by gotkrypto76** [comment]
Hey!

Thanks for contacting me to let me know about this issue! I’ll see what I can do, and push an update to solve it asap.

**Comment by gotkrypto76** [comment]
This issue should be resolved as of the latest commit.
